services:
  frontend:
    build: ./frontend
    expose:
      - "4173"
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - uploads_data:/app/uploads
    networks:
      - app-net

  # admin-service:
  #   build: ./admin-service
  #   depends_on:
  #     - keycloak
  #   networks:
  #     - app-net

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    networks:
      - app-net
    ports:
      - "27017:27017"

  proxy:
    build: ./proxy
    ports:
      - "3000:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD_FILE: /run/secrets/keycloakAdminPassword
    secrets:
      - keycloakAdminPassword
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "8080:8080"
    networks:
      - app-net

volumes:
  mongo_data:
  keycloak_data:
  uploads_data:

networks:
  app-net:
    driver: bridge

secrets:
  keycloakAdminPassword:
    file: ./secrets/keycloakAdminPassword.txt
