services:
  frontend:
    build: ./frontend
    expose:
      - "4173"
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - postgres
    volumes:
      - uploads_data:/app/uploads
    environment:
      - DATABASE_URL=postgresql://carxuser:carxpass@postgres:5432/carxauth
    networks:
      - app-net

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - app-net
    ports:
      - "27017:27017"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: carxauth
      POSTGRES_USER: carxuser
      POSTGRES_PASSWORD: carxpass
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-net

  proxy:
    build: ./proxy
    ports:
      - "3000:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-net

volumes:
  mongo_data:
  pg_data:
  uploads_data:
  mongo_config:

networks:
  app-net:
    driver: bridge
