apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ../k8s
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ../k8s
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://carxuser:carxpass@postgres:5432/carxauth
          image: janjus/carx-backend:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:5000/me
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: backend
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /app/uploads
              name: uploads-data
      restartPolicy: Always
      volumes:
        - name: uploads-data
          persistentVolumeClaim:
            claimName: uploads-data
