apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ../k8s
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: "4173"
      port: 4173
      targetPort: 4173
  selector:
    io.kompose.service: frontend
