apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ../k8s
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ../k8s
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6
          command: ["mongod", "--bind_ip_all"]
          # livenessProbe:
          #   exec:
          #     command:
          #       - echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
          #   failureThreshold: 3
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
            - mountPath: /data/configdb
              name: mongo-config
      restartPolicy: Always
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data
        - name: mongo-config
          persistentVolumeClaim:
            claimName: mongo-config
