apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  hostPath:
    path: /tmp/k8s/mongo-data
