apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-data-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  hostPath:
    path: /tmp/k8s/pg-data
