apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: uploads-data
  name: uploads-data
spec:
  volumeName: uploads-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
