apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongo-config
  name: mongo-config
spec:
  volumeName: mongo-config-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
