apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ../k8s
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proxy
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ../k8s
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: proxy
    spec:
      containers:
        - image: janjus/carx-proxy:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: proxy
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      restartPolicy: Always
